"""Event manager info update

Revision ID: 7eb0648f98b7
Revises: 
Create Date: 2024-08-29 09:21:44.935249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb0648f98b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('manager_login', sa.String(), nullable=False))
    op.add_column('events', sa.Column('manager_fullname', sa.String(), nullable=False))
    op.drop_column('events', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('manager_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('events', 'manager_fullname')
    op.drop_column('events', 'manager_login')
    # ### end Alembic commands ###
